M48
; DRILL file {KiCad 9.0.4} date 2026-05-30T13:30:46-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-30T13:30:46-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X55.44Y-76.71
X55.44Y-82.49
T2
X54.0Y-54.0
X54.0Y-106.0
X96.0Y-54.0
X96.0Y-106.0
M30
